version: '3.8'

services:
  backend:
    build:
      context: ../../../material-applications/example-backend
    ports:
      - 8080:8080
    environment:
      REQUEST_ORIGIN: http://localhost:8000
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: the-boy-who-cried-wolf
  frontend:
    build:
      args:
        REACT_APP_BACKEND_URL: http://localhost:8080
      context: ../../../material-applications/example-frontend
    ports:
      - 8000:5000
  redis:
    image: redis:latest
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: the-boy-who-cried-wolf
